### ISSUE TITLE
Axon tokio-runtime-worker panic

### ISSUE THREAD

**Issue by jiangxianliang007** [axonweb3/axon#1282]
### Current Behavior

A bug happened!
chain height 1226198
run https://github.com/godwokenrises/godwoken-tests/actions/runs/5657469155/job/15327443180   axon is panic.

### Expected Behavior

Expected Behavior:

### OS

Ubuntu 18.04.2 

### Axon version

axon 0.1.0-beta.5 7417d44

### Kernel

Linux axon-node-explorer 5.4.0-1101-aws #109~18.04.1-Ubuntu SMP Mon Apr 24 20:40:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Relevant log output

```
{"time":"2023-07-25T13:57:36.801560284+00:00","message":"EVM event Call { code_address: 0x966b30e576a4d6731996748b48dd67c94ef29067, transfer: Some(Transfer { source: 0xf386573563c3a75dbbd269fce9782620826ddac2, target: 0x966b30e576a4d6731996748b48dd67c94ef29067, value: 100000000000 }), input: [], target_gas: Some(3
0000000), is_static: false, context: Context { address: 0x966b30e576a4d6731996748b48dd67c94ef29067, caller: 0xf386573563c3a75dbbd269fce9782620826ddac2, apparent_value: 100000000000 } }","module_path":"core_executor::tracing","file":"core/executor/src/tracing.rs","line":128,"level":"INFO","target":"core_executor::tracing","thread":"tokio-runtime-worker","thread_id":139790048544512,"mdc":{}}{"time":"2023-07-25T13:57:36.801609416+00:00","message":"EVM event Exit { reason: Error(OutOfFund), return_value: [] }","module_path":"core_executor::tracing","file":"core/executor/src/tracing.rs","line":128,"level":"INFO","target":"core_executor::tracing","thread":"tokio-runtime-worker","thread_id":13979004854451
2,"mdc":{}}{"time":"2023-07-25T13:57:36.881931036+00:00","message":"thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: \"No logs\"': /home/ckb/build-axon/axon/core/executor/src/lib.rs:313    0: core_run::Axon::panic_log\n   1: core_run::Axon::set_ctrl_c_handle::{{closure}}::{{closure}}\n 
  2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9\n      std::panicking::rust_panic_with_hook\n             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13\n   3: std::panicking::begin_panic_handler::{{closure}}\n             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13\n   4: std::sys_common::backtrace::__rust_end_short_backtrace\n             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18\n   5: rust_begin_unwind\n             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5\n   6: core::panicking::panic_fmt\n             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14\n   7: core::result::unwrap_failed\n             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5\n   8: core_executor::AxonExecutor::tracing_call\n   9: <core_api::adapter::DefaultAPIAdapter<M,S,DB,Net> as axon_protocol::traits::api::APIAdapter>::evm_call::{{closure}}\n  10: core_api::jsonrpc::impl::web3::Web3RpcImpl<Adapter>::call_evm::{{closure}}\n  11: <core::pin::Pin<P> as core::future::future::Future>::poll\n  12: <core_api::jsonrpc::impl::web3::Web3RpcImpl<Adapter> as core_api::jsonrpc::Web3RpcServer>::estimate_gas::{{closure}}\n  13: jsonrpsee_core::server::rpc_module::RpcModule<Context>::register_async_method::{{closure}}::{{closure}}\n  14: jsonrpsee_server::transport::http::process_validated_request::{{closure}}\n  15: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll\n  16: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch\n  17: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll\n  18: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll\n  19: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll\n  20: jsonrpsee_server::future::FutureDriver<F>::drive\n  21: jsonrpsee_server::server::Server<B,L>::start_inner::{{closure}}\n  22: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut\n  23: tokio::runtime::task::core::Core<T,S>::poll\n  24: tokio::runtime::task::harness::Harness<T,S>::poll\n  25: tokio::runtime::scheduler::multi_thread::worker::Context::run_task\n  26: tokio::runtime::scheduler::multi_thread::worker::Context::run\n  27: tokio::runtime::context::scoped::Scoped<T>::set\n  28: tokio::runtime::context::runtime::enter_runtime\n  29: tokio::runtime::scheduler::multi_thread::worker::run\n  30: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut\n  31: tokio::runtime::task::core::Core<T,S>::poll\n  32: tokio::runtime::task::harness::Harness<T,S>::poll\n  33: tokio::runtime::blocking::pool::Inner::run\n  34: std::sys_common::backtrace::__rust_begin_short_backtrace\n  35: core::ops::function::FnOnce::call_once{{vtable.shim}}\n  36: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17\n  37: start_thread\n  38: clone\n","module_path":"core_run","file":"core/run/src/lib.rs","line":861,"level":"ERROR","target":"panic","thread":"tokio-runtime-worker","thread_id":139790048544512,"mdc":{}}{"time":"2023-07-25T13:57:36.884048006+00:00","message":"child thread panic, quit.","module_path":"core_run","file":"core/run/src/lib.rs","line":835,"level":"INFO","target":"core_run","thread":"main","thread_id":139790082933760,"mdc":{}}
```

**Comment by jiangxianliang007** [comment]
```[2023-07-25T14:11:27.621313989+00:00 INFO core_consensus::engine] [consensus]: validator of number 335 is [bls public key "ac85bbb4", public key Hex("0x031ddc35212b7fc7ff6685b17d91f77c972535aee5c7ae5684d3e72b986f08834b"), address 0x8ab0cf264df99d83525e9e11c7e4db01558ae1b1 propose weight 1, vote weight 1]
[2023-07-25T14:11:27.621515995+00:00 INFO core_mempool] [core_mempool]: flush mempool with 0 tx_hashes
[2023-07-25T14:11:27.621713096+00:00 INFO overlord::state::process] Overlord: achieve consensus in height 334, costs 1 round 3.643582ms time
[2023-07-25T14:11:28.171923807+00:00 INFO jsonrpsee_server::server] Accepting new connection 1/25000
[2023-07-25T14:11:28.175731745+00:00 INFO jsonrpsee_server::server] Accepting new connection 2/25000
[2023-07-25T14:11:28.976221080+00:00 INFO core_executor::tracing] EVM event TransactCall { caller: 0xf386573563c3a75dbbd269fce9782620826ddac2, address: 0x966b30e576a4d6731996748b48dd67c94ef29067, value: 100000000000, data: [], gas_limit: 30000000 }
[2023-07-25T14:11:28.976339740+00:00 INFO core_executor::tracing] EVM event Call { code_address: 0x966b30e576a4d6731996748b48dd67c94ef29067, transfer: Some(Transfer { source: 0xf386573563c3a75dbbd269fce9782620826ddac2, target: 0x966b30e576a4d6731996748b48dd67c94ef29067, value: 100000000000 }), input: [], target_ga
s: Some(30000000), is_static: false, context: Context { address: 0x966b30e576a4d6731996748b48dd67c94ef29067, caller: 0xf386573563c3a75dbbd269fce9782620826ddac2, apparent_value: 100000000000 } }[2023-07-25T14:11:28.976379212+00:00 INFO core_executor::tracing] EVM event Exit { reason: Error(OutOfFund), return_value: [] }
[2023-07-25T14:11:28.987864589+00:00 ERROR panic] thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: "No logs"': /build/core/executor/src/lib.rs:313    0: core_run::Axon::panic_log
   1: core_run::Axon::set_ctrl_c_handle::{{closure}}::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
      std::panicking::rust_panic_with_hook
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
   5: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   6: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   7: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
   8: core_executor::AxonExecutor::tracing_call
   9: <core_api::adapter::DefaultAPIAdapter<M,S,DB,Net> as axon_protocol::traits::api::APIAdapter>::evm_call::{{closure}}
  10: core_api::jsonrpc::impl::web3::Web3RpcImpl<Adapter>::call_evm::{{closure}}
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
  12: <core_api::jsonrpc::impl::web3::Web3RpcImpl<Adapter> as core_api::jsonrpc::Web3RpcServer>::estimate_gas::{{closure}}
  13: jsonrpsee_core::server::rpc_module::RpcModule<Context>::register_async_method::{{closure}}::{{closure}}
  14: jsonrpsee_server::transport::http::process_validated_request::{{closure}}
  15: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  16: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  17: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  18: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  19: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  20: jsonrpsee_server::future::FutureDriver<F>::drive
  21: jsonrpsee_server::server::Server<B,L>::start_inner::{{closure}}
  22: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  23: tokio::runtime::task::core::Core<T,S>::poll
  24: tokio::runtime::task::harness::Harness<T,S>::poll
  25: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  26: tokio::runtime::scheduler::multi_thread::worker::Context::run
  27: tokio::runtime::context::scoped::Scoped<T>::set
  28: tokio::runtime::context::runtime::enter_runtime
  29: tokio::runtime::scheduler::multi_thread::worker::run
  30: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  31: tokio::runtime::task::core::Core<T,S>::poll
  32: tokio::runtime::task::harness::Harness<T,S>::poll
  33: tokio::runtime::blocking::pool::Inner::run
  34: std::sys_common::backtrace::__rust_begin_short_backtrace
  35: core::ops::function::FnOnce::call_once{{vtable.shim}}
  36: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
  37: <unknown>
  38: <unknown>

[2023-07-25T14:11:28.988153337+00:00 INFO core_run] child thread panic, quit.
```
