### ISSUE TITLE
Transaction Hash Mismatch

### ISSUE THREAD

**Issue by distributedstatemachine** [axonweb3/axon#724]
**What happened**:

When trying to send  raw transactions , we encounter this error:

```
Error: web3 RPC failed: {"code":-32001,"message":"Custom error: [ProtocolError] Kind: Types Error: TxHashMismatch { origin: 0xede84189f814dad023f7dfc986bc2e0573bf9fa0ac24baed321471cf370102a0, calc: 0xb6331134996b4acde9814fc445e26061ef3b13148c3a50cad67d453174bf9bed }"}
    at sendNodeRequest (/Users/samueldare/Parity/tokenbridge-contracts/deploy/src/deploymentUtils.js:161:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendRawTx (/Users/samueldare/Parity/tokenbridge-contracts/deploy/src/deploymentUtils.js:130:20)
    at async deployContract (/Users/samueldare/Parity/tokenbridge-contracts/deploy/src/deploymentUtils.js:55:14)
    at async deployHome (/Users/samueldare/Parity/tokenbridge-contracts/deploy/src/arbitrary_message/home.js:82:33)
    at async deployArbitraryMessage (/Users/samueldare/Parity/tokenbridge-contracts/deploy/deploy.js:39:26)
    at async main (/Users/samueldare/Parity/tokenbridge-contracts/deploy/deploy.js:90:7)
Error: TypeError: Cannot read property 'status' of undefined
    at deployContract (/Users/samueldare/Parity/tokenbridge-contracts/deploy/src/deploymentUtils.js:63:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async deployHome (/Users/samueldare/Parity/tokenbridge-contracts/deploy/src/arbitrary_message/home.js:82:33)
    at async deployArbitraryMessage (/Users/samueldare/Parity/tokenbridge-contracts/deploy/deploy.js:39:26)
    at async main (/Users/samueldare/Parity/tokenbridge-contracts/deploy/deploy.js:90:7)
   ```

The axon RPC seems to be mutating the hash and causing this error. 

**What you expected to happen**:

Transaction should be successful.

**How to reproduce it (as minimally and precisely as possible)**:
* Run [this](https://github.com/samtvlabs/tokenbridge-contracts/tree/master/deploy)

**Anything else we need to know?**:

**Environment**:

Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 x86_64

**Comment by KaoImin** [comment]
This problem appears to be because the `chain_id` is not included in the transaction. In this case, we were not compatible with these transactions previously, because we thought the `chain_id` is necessary. Do you have to use a transaction that without a `chain_id`?

**Comment by distributedstatemachine** [comment]
We have upgraded an intermediate library which seems to have solved this.
